;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cider-repl-tab
        cljr-slash
        clojure-convert-collection-to-list
        clojure-convert-collection-to-map
        clojure-convert-collection-to-set
        clojure-convert-collection-to-vector
        comment-indent-new-line
        crux-move-beginning-of-line
        delete-horizontal-space
        easy-kill
        indent-for-tab-command
        shrink-whitespace
        sp-backward-barf-sexp
        sp-backward-delete-char
        sp-backward-down-sexp
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-slurp-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-barf-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-join-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        sp-splice-sexp
        sp-splice-sexp-killing-around
        sp-splice-sexp-killing-backward
        sp-splice-sexp-killing-forward
        sp-split-sexp
        sp-up-sexp
        sp-wrap-round
        transpose-sexps
        transpose-words
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        beginning-of-buffer
        cider-load-buffer
        describe-key
        end-of-buffer
        helm-confirm-and-exit-minibuffer
        helm-projectile-find-file
        helm-show-kill-ring
        scroll-other-window
        ))
